/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogCadastro.java
 *
 * Created on 21/04/2011, 16:35:46
 */

package siscadfj.view;









import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import siscadfj.controller.SocioBD;
import siscadfj.model.Socio;
import siscadfj.view.JFramePrinciapal;

/**
 *
 * @author stevao
 */
public class JDialogCadastro extends javax.swing.JDialog {
    private Frame JFramePrinciapal;

    /** Creates new form JDialogCadastro */
    public JDialogCadastro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        iniciar();

        
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxBloco = new javax.swing.JComboBox();
        jLabelEstado = new javax.swing.JLabel();
        jComboBoxDia = new javax.swing.JComboBox();
        jTextFieldNome = new javax.swing.JTextField();
        jComboBoxAno = new javax.swing.JComboBox();
        jLabelBairro = new javax.swing.JLabel();
        jComboBoxMes = new javax.swing.JComboBox();
        jLabelCidade = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox();
        jLabelCelular = new javax.swing.JLabel();
        jLabelFuncao = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox();
        jLabelTelefone = new javax.swing.JLabel();
        jComboBoxFuncao = new javax.swing.JComboBox();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldNum = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelCpf = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelBloco = new javax.swing.JLabel();
        jLabelRg = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jLabelMatricula = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jLabelDtNasc = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        javax.swing.text.MaskFormatter maskFone = null;
        try{
            maskFone = new javax.swing.text.MaskFormatter("(##)####-####");
        }
        catch(java.text.ParseException exc){}
        jFormattedTextFieldFone = new javax.swing.JFormattedTextField(maskFone);
        javax.swing.text.MaskFormatter maskCel = null;
        try{
            maskCel = new javax.swing.text.MaskFormatter("(##)####-####");
        }
        catch(java.text.ParseException exc){}
        jFormattedTextFieldCel = new javax.swing.JFormattedTextField(maskCel);
        javax.swing.text.MaskFormatter maskCPF = null;
        try{
            maskCPF = new javax.swing.text.MaskFormatter("###.###.###-##");
        }
        catch(java.text.ParseException exc){}

        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField(maskCPF);
        javax.swing.text.MaskFormatter maskMat = null;
        try{
            maskMat = new javax.swing.text.MaskFormatter("########");
        }
        catch(java.text.ParseException exc){}
        jFormattedTextFieldMatricula = new javax.swing.JFormattedTextField(maskMat);
        jFormattedTextFieldRg = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Socios - SISCadFJ");

        jComboBoxBloco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "1° Período", "2° Período", "3° Período", "4° Período", "5° Período", "6° Período", "7° Período", "8° Período" }));
        jComboBoxBloco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBlocoActionPerformed(evt);
            }
        });

        jLabelEstado.setText("Estado:");

        jComboBoxDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jComboBoxAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011" }));

        jLabelBairro.setText("Bairro:");

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        jLabelCidade.setText("Cidade:");

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Piauí- PI", "Acre - AC", "Alagoas - AL", "Amapá - AP", "Amazonas - AM", "Bahia  - BA", "Ceará - CE", "Distrito Federal  - DF", "Espírito Santo - ES", "Goiás - GO", "Maranhão - MA", "Mato Grosso - MT", "Mato Grosso do Sul - MS", "Minas Gerais - MG", "Pará - PA", "Paraíba - PB", "Paraná - PR", "Pernambuco - PE", "Rio de Janeiro - RJ", "Rio Grande do Norte - RN", "Rio Grande do Sul - RS", "Rondônia - RO", "Roraima - RR", "Santa Catarina - SC", "São Paulo - SP", "Sergipe - SE", "Tocantins - TO" }));

        jLabelCelular.setText("Celular:");

        jLabelFuncao.setText("Função:");

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        jComboBoxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSexoActionPerformed(evt);
            }
        });

        jLabelTelefone.setText("Telefone:");

        jComboBoxFuncao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Colaborador", "Diretoria", "Estagiário" }));
        jComboBoxFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFuncaoActionPerformed(evt);
            }
        });

        jLabelEmail.setText("Email:");

        jLabelCpf.setText("Cpf:");

        jLabelNome.setText("Nome:");

        jLabelNumero.setText("N°:");

        jLabelBloco.setText("Bloco:");

        jLabelRg.setText("RG:");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelMatricula.setText("Matrícula:");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jLabelDtNasc.setText("Dt Nasc.:");

        jLabelEndereco.setText("Endereço:");

        jLabelSexo.setText("Sexo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelTelefone)
                                    .addComponent(jLabelBairro)
                                    .addComponent(jLabelEndereco)
                                    .addComponent(jLabelNome)
                                    .addComponent(jLabelCpf)
                                    .addComponent(jLabelMatricula)
                                    .addComponent(jLabelDtNasc))
                                .addGap(1, 1, 1))
                            .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jFormattedTextFieldMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                                        .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                                        .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                                .addComponent(jFormattedTextFieldFone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabelCidade)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabelCelular)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jFormattedTextFieldCel, 0, 0, Short.MAX_VALUE)))))
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelBloco)
                                        .addComponent(jLabelFuncao)
                                        .addComponent(jLabelRg)
                                        .addComponent(jLabelEstado)
                                        .addComponent(jLabelNumero))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jFormattedTextFieldRg)
                                        .addComponent(jComboBoxFuncao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jTextFieldNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                                .addComponent(jComboBoxBloco, 0, 60, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelSexo)
                                            .addGap(1, 1, 1)
                                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCpf)
                    .addComponent(jLabelRg)
                    .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBloco)
                    .addComponent(jLabelMatricula)
                    .addComponent(jComboBoxBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSexo)
                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDtNasc)
                    .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEndereco)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumero))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBairro)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCidade)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstado)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefone)
                    .addComponent(jLabelCelular)
                    .addComponent(jFormattedTextFieldFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFuncao)
                    .addComponent(jComboBoxFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-809)/2, (screenSize.height-456)/2, 809, 456);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxBlocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBlocoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBoxBlocoActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jComboBoxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSexoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBoxSexoActionPerformed

    private void jComboBoxFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFuncaoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBoxFuncaoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:

        //Evento para fechar Form
        int i = JOptionPane.showConfirmDialog(this, "Deseja cancelar cadastro?", "Fechar", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_NO_OPTION) {
            this.dispose();
        }
}//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
                
            if(jTextFieldNome.getText().equals("") ){

                JOptionPane.showMessageDialog(this, "Campo obrigatorio!", "Atenção", JOptionPane.OK_OPTION);
                jTextFieldNome.grabFocus();
            }

            else

            if(jFormattedTextFieldCpf.getText().equals("") ){

                JOptionPane.showMessageDialog(this, "Campo obrigatorio!", "Atenção", JOptionPane.OK_OPTION);
                jFormattedTextFieldCel.grabFocus();
            }

            else

            if(jFormattedTextFieldRg.getText().equals("") ){

                JOptionPane.showMessageDialog(this, "Campo obrigatorio!", "Atenção", JOptionPane.OK_OPTION);
                jFormattedTextFieldRg.grabFocus();
            }

            else

            if(jFormattedTextFieldMatricula.getText().equals("") ){

                JOptionPane.showMessageDialog(this, "Campo obrigatorio!", "Atenção", JOptionPane.OK_OPTION);
                jFormattedTextFieldMatricula.grabFocus();
            }

            else

            if(jTextFieldEndereco.getText().equals("") ){

                JOptionPane.showMessageDialog(this, "Campo obrigatorio!", "Atenção", JOptionPane.OK_OPTION);
                jTextFieldEndereco.grabFocus();
            }

            else

            if(jTextFieldNum.getText().equals("") ){

                JOptionPane.showMessageDialog(this, "Campo obrigatorio!", "Atenção", JOptionPane.OK_OPTION);
                jTextFieldNum.grabFocus();
            }

            else

            if(jTextFieldBairro.getText().equals("") ){

                JOptionPane.showMessageDialog(this, "Campo obrigatorio!", "Atenção", JOptionPane.OK_OPTION);
                jTextFieldBairro.grabFocus();
            }

            else

            if(jTextFieldCidade.getText().equals("") ){

                JOptionPane.showMessageDialog(this, "Campo obrigatorio!", "Atenção", JOptionPane.OK_OPTION);
                jTextFieldCidade.grabFocus();
            }

            else


            if(jFormattedTextFieldFone.getText().equals("") ){

                JOptionPane.showMessageDialog(this, "Campo obrigatorio!", "Atenção", JOptionPane.OK_OPTION);
                jFormattedTextFieldFone.grabFocus();
            }

            else

           
            if(jFormattedTextFieldCel.getText().equals("") ){

                JOptionPane.showMessageDialog(this, "Campo obrigatorio!", "Atenção", JOptionPane.OK_OPTION);
                jFormattedTextFieldCel.grabFocus();
            }

            else

            if(jTextFieldEmail.getText().equals("") ){

                JOptionPane.showMessageDialog(this, "Campo obrigatorio!", "Atenção", JOptionPane.OK_OPTION);
                jTextFieldEmail.grabFocus();
            }

            else{

                SocioBD socio = new SocioBD();

            int i = JOptionPane.showConfirmDialog(this, "Deseja cadastrar o Socio?", "Informação", JOptionPane.YES_NO_OPTION);
            if (i == JOptionPane.YES_NO_OPTION) {
            socio.inserirSocio(getDadosDialogCadastro());
JOptionPane.showMessageDialog(this, "Socio Cadastrado com sucesso!", "Parabéns", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);

            //Inicia Dialog de habilidades
            JDialogHabilidade dialog =new JDialogHabilidade(JFramePrinciapal,true);
                dialog.setVisible(true);

            }
            
        }
            
            
            
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogCadastro dialog = new JDialogCadastro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxAno;
    private javax.swing.JComboBox jComboBoxBloco;
    private javax.swing.JComboBox jComboBoxDia;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxFuncao;
    private javax.swing.JComboBox jComboBoxMes;
    private javax.swing.JComboBox jComboBoxSexo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCel;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldFone;
    private javax.swing.JFormattedTextField jFormattedTextFieldMatricula;
    private javax.swing.JFormattedTextField jFormattedTextFieldRg;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelBloco;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelDtNasc;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFuncao;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelRg;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNum;
    // End of variables declaration//GEN-END:variables

        //Metodo para pegar dados dos campos do Form.
    private Socio getDadosDialogCadastro(){//CORRIGIR Construtor
        Socio socio = new Socio();
        socio.setNome((this.jTextFieldNome.getText()));
        socio.setCpf(this.jFormattedTextFieldCpf.getText());
        socio.setRg((this.jFormattedTextFieldRg.getText()));
        socio.setMatricula(this.jFormattedTextFieldMatricula.getText());
        socio.setSexo((String) this.jComboBoxSexo.getSelectedItem());
        socio.setDia((String) this.jComboBoxDia.getSelectedItem());
        socio.setMes((String) this.jComboBoxMes.getSelectedItem());
        socio.setAno((String) this.jComboBoxAno.getSelectedItem());
        socio.setEndereco(this.jTextFieldEndereco.getText());
        socio.setNumEndereco(this.jTextFieldNum.getText());
        socio.setBairro(this.jTextFieldBairro.getText());
        socio.setCidade(this.jTextFieldCidade.getText());
        socio.setEstado((String) this.jComboBoxEstado.getSelectedItem());
        socio.setEmail(this.jTextFieldEmail.getText());
        socio.setFone(this.jFormattedTextFieldFone.getText());
        socio.setCel(this.jFormattedTextFieldCel.getText());
        socio.setBloco((String) this.jComboBoxBloco.getSelectedItem());
        socio.setFuncao((String)this.jComboBoxFuncao.getSelectedItem());

        return socio;
    }


    private void iniciar(){
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setModal(true);
        this.setResizable(false);

    }




}
