/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogRelatorio.java
 *
 * Created on 06/06/2011, 18:50:33
 */

package siscadfj.view;



import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import siscadfj.controller.Relatorios;
import siscadfj.controller.SocioBD;
import siscadfj.model.Socio;



/**
 *
 * @author fj_informatica
 */
public class JDialogRelatorio extends javax.swing.JDialog {

    /** Creates new form JDialogRelatorio */
    public JDialogRelatorio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEmitir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxHablidades = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jComboBoxSocio = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Relatorio de Socios - SISCADFJ");
        setModal(true);
        setName("dialogRelatorio"); // NOI18N
        setResizable(false);

        jButtonEmitir.setText("Emitir");
        jButtonEmitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmitirActionPerformed(evt);
            }
        });

        jLabel1.setText("Relatorio de Socios:");

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Relatorio de Habilidades:");

        jComboBoxHablidades.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Banco de Dados", "CSS", "C", "IA", "Java", "Suporte", "Delphi", "Design", "HTML", "PHP", "Redes", "Ruby" }));

        jButton2.setText("Emitir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBoxSocio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Relatorio Geral", "Relatorio Individual" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxSocio, 0, 0, Short.MAX_VALUE)
                            .addComponent(jComboBoxHablidades, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEmitir)
                            .addComponent(jButton2))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxHablidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEmitir))
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-491)/2, (screenSize.height-258)/2, 491, 258);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEmitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmitirActionPerformed

        relatorioSocios();
    
       
    }//GEN-LAST:event_jButtonEmitirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

         int i = JOptionPane.showConfirmDialog(this, "Deseja realmente sair?", "Fechar", JOptionPane.YES_NO_OPTION);
            if (i == JOptionPane.YES_NO_OPTION) {
              this.dispose();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        relatorioHabilidades();

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogRelatorio dialog = new JDialogRelatorio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonEmitir;
    private javax.swing.JComboBox jComboBoxHablidades;
    private javax.swing.JComboBox jComboBoxSocio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void emitirRelatorio(String nomeRelatorio){

        Relatorios relatorio = new Relatorios();

        relatorio.geraRelatorio(nomeRelatorio);
}

    private void relatorioHabilidades(){

        String nome = (String)jComboBoxHablidades.getSelectedItem();

        if(nome.equals("Banco de Dados"))
                emitirRelatorio("relatorioBD");

        if(nome.equals("C"))
                emitirRelatorio("relatorioC");
  
        if(nome.equals("CSS"))
                emitirRelatorio("relatorioCSS");

        if(nome.equals("Delphi"))
                emitirRelatorio("relatorioDelphi");

        if(nome.equals("Design"))
                emitirRelatorio("relatorioDesign");

        if(nome.equals("HTML"))
                emitirRelatorio("relatorioHTML");

        if(nome.equals("IA"))
                emitirRelatorio("relatorioIA");

        if(nome.equals("Java"))
                emitirRelatorio("relatorioJava");

        if(nome.equals("PHP"))
                emitirRelatorio("relatorioPHP");

        if(nome.equals("Redes"))
                emitirRelatorio("relatorioRedes");

        if(nome.equals("Ruby"))
                emitirRelatorio("relatorioRuby");

        if(nome.equals("Suporte"))
                emitirRelatorio("relatorioSuporte");
    }//Fim do relatorio de atividades


    private void relatorioSocios(){

        String nome = (String)jComboBoxSocio.getSelectedItem();

        if(nome.equals("Relatorio Geral"))
                emitirRelatorio("relatorioGeral");

        if(nome.equals("Relatorio Individual")){
                JDialogIndividual dialog = new JDialogIndividual(null, true);
                        dialog.setVisible(true);
        }
    }

    
                
    
}



