/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogHabilidade.java
 *
 * Created on 21/04/2011, 16:42:52
 */

package siscadfj.view;

import javax.swing.JOptionPane;
import siscadfj.controller.HabilidadeBD;
import siscadfj.controller.SocioBD;
import siscadfj.model.HabilidadeValor;
import siscadfj.model.Socio;


/**
 *
 * @author stevao
 */
public class JDialogHabilidade extends javax.swing.JDialog {

    /** Creates new form JDialogHabilidade */
    public JDialogHabilidade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        iniciar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHabilidades = new javax.swing.JLabel();
        jCheckBoxRedes = new javax.swing.JCheckBox();
        jCheckBoxPhp = new javax.swing.JCheckBox();
        jCheckBoxRuby = new javax.swing.JCheckBox();
        jCheckBoxIa = new javax.swing.JCheckBox();
        jCheckBoxManutencao = new javax.swing.JCheckBox();
        jCheckBoxJava = new javax.swing.JCheckBox();
        jCheckBoxHtml = new javax.swing.JCheckBox();
        jCheckBoxDelphi = new javax.swing.JCheckBox();
        jLabelOutros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonSalvar1 = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jCheckBoxCss = new javax.swing.JCheckBox();
        jCheckBoxClinguagem = new javax.swing.JCheckBox();
        jCheckBoxBancodedados = new javax.swing.JCheckBox();
        jCheckBoxDesigngrafico = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Habilidades - SISCadFJ");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabelHabilidades.setText("Habilidades:");

        jCheckBoxRedes.setText("Redes");

        jCheckBoxPhp.setText("PHP");

        jCheckBoxRuby.setText("Ruby");

        jCheckBoxIa.setText("Inteligencia Artificial");

        jCheckBoxManutencao.setText("Manutenção/Suporte");

        jCheckBoxJava.setText("Java");

        jCheckBoxHtml.setText("HTML");

        jCheckBoxDelphi.setText("Pascal/Delphi");

        jLabelOutros.setText("Outros:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonSalvar1.setText("Salvar");
        jButtonSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvar1ActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelNome.setText("Nome:");

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jCheckBoxCss.setText("CSS");
        jCheckBoxCss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCssActionPerformed(evt);
            }
        });

        jCheckBoxClinguagem.setText("C/C++");
        jCheckBoxClinguagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxClinguagemActionPerformed(evt);
            }
        });

        jCheckBoxBancodedados.setText("Banco de dados");

        jCheckBoxDesigngrafico.setText("Design Gráfico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelOutros)
                            .addComponent(jLabelHabilidades)
                            .addComponent(jLabelNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxCss)
                                    .addComponent(jCheckBoxClinguagem)
                                    .addComponent(jCheckBoxBancodedados))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxJava)
                                    .addComponent(jCheckBoxManutencao)
                                    .addComponent(jCheckBoxIa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxDesigngrafico)
                                    .addComponent(jCheckBoxHtml)
                                    .addComponent(jCheckBoxDelphi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxPhp)
                                    .addComponent(jCheckBoxRuby)
                                    .addComponent(jCheckBoxRedes)))
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBoxJava)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxBancodedados)
                                    .addComponent(jCheckBoxIa)
                                    .addComponent(jLabelHabilidades))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxCss)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxManutencao)
                            .addComponent(jCheckBoxClinguagem)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBoxDesigngrafico)
                                .addComponent(jCheckBoxRedes))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxDelphi)
                                    .addComponent(jCheckBoxPhp))
                                .addGap(26, 26, 26)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxHtml)
                            .addComponent(jCheckBoxRuby))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOutros))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-707)/2, (screenSize.height-469)/2, 707, 469);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvar1ActionPerformed
        // TODO add your handling code here:


        HabilidadeBD habilidade = new HabilidadeBD();

        //Insere habilidades marcadas
        int i = JOptionPane.showConfirmDialog(this, "Deseja cadastrar habilidades selecionadas?", "Informação", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_NO_OPTION) {
            habilidade.inserirHabilidade(getDadosDialogHab());
            JOptionPane.showMessageDialog(this, "Habilidades Cadastrado com sucesso!", "Parabéns", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }
        

}//GEN-LAST:event_jButtonSalvar1ActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
                //Metodo para sair
        int i = JOptionPane.showConfirmDialog(this, "Deseja não cadastrar habilidades?", "Fechar", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_NO_OPTION) {
            this.dispose();
        }


    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jCheckBoxCssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCssActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jCheckBoxCssActionPerformed

    private void jCheckBoxClinguagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxClinguagemActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jCheckBoxClinguagemActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:


    }//GEN-LAST:event_formComponentShown

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogHabilidade dialog = new JDialogHabilidade(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar1;
    private javax.swing.JCheckBox jCheckBoxBancodedados;
    private javax.swing.JCheckBox jCheckBoxClinguagem;
    private javax.swing.JCheckBox jCheckBoxCss;
    private javax.swing.JCheckBox jCheckBoxDelphi;
    private javax.swing.JCheckBox jCheckBoxDesigngrafico;
    private javax.swing.JCheckBox jCheckBoxHtml;
    private javax.swing.JCheckBox jCheckBoxIa;
    private javax.swing.JCheckBox jCheckBoxJava;
    private javax.swing.JCheckBox jCheckBoxManutencao;
    private javax.swing.JCheckBox jCheckBoxPhp;
    private javax.swing.JCheckBox jCheckBoxRedes;
    private javax.swing.JCheckBox jCheckBoxRuby;
    private javax.swing.JLabel jLabelHabilidades;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelOutros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables

    private void iniciar(){
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setModal(true);
        this.setResizable(false);
        insereCampo();
    }

    //Insere nome do socio ao TextFildNome
    private void insereCampo(){

        //Objeto para pegar insformaões do socio "Nome,Matricula,Bloco,ID"
        SocioBD  socioBD = new SocioBD();

        //Objeto socio para receber as informações
        Socio socio = new Socio();

        socio = socioBD.getSocioInfo();

        jTextFieldNome.setText(socio.getNome());

        jTextFieldNome.setEnabled(false);

    }

    private HabilidadeValor getDadosDialogHab(){

        HabilidadeValor habList = new HabilidadeValor();

        habList.setBancoDeDados(this.jCheckBoxBancodedados.isSelected());
        habList.setC(this.jCheckBoxClinguagem.isSelected());
        habList.setCss(this.jCheckBoxCss.isSelected());
        habList.setDelphi(this.jCheckBoxDelphi.isSelected());
        habList.setDesign(this.jCheckBoxDesigngrafico.isSelected());
        habList.setHtml(this.jCheckBoxHtml.isSelected());
        habList.setIa(this.jCheckBoxIa.isSelected());
        habList.setJava(this.jCheckBoxJava.isSelected());
        habList.setPhp(this.jCheckBoxPhp.isSelected());
        habList.setRedes(this.jCheckBoxRedes.isSelected());
        habList.setSuporte(this.jCheckBoxManutencao.isSelected());
        habList.setRuby(this.jCheckBoxRuby.isSelected());
        habList.setOutros(this.jTextArea1.getText());

        return habList;
    }


}
